Added ping_pong example
microROS/apps pull request #23
Opened 2020-04-27 15:20 UTC by pablogs9

This PR adds the code fo the example [here](https://micro-ros.github.io/docs/tutorials/core/first_application_rtos/)

2020-04-28 08:12 UTC, ralph-lange requested changes

2020-04-28 08:12 UTC, ralph-lange commented on examples/uros_pingpong/uros_pingpong_main.c
> +  rcl_init_options_t options = rcl_get_zero_initialized_init_options();
The initialization can be simplified by rclc_support_init and rclc_node_init_default, cf. https://github.com/micro-ROS/rclc/blob/master/rclc_examples/src/example_executor_convenience.c#L57
We should use the convencience functions from rclc in all our tutorials.

2020-04-28 08:12 UTC, ralph-lange commented on examples/uros_pingpong/uros_pingpong_main.c
> +  rcl_publisher_init(&ping_publisher, &node, ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Header), "/microROS/ping", &ping_publisher_ops);
Use rclc_publisher_init_default instead, to reduce the amount of boilerplate code, cf. https://github.com/micro-ROS/rclc/blob/master/rclc_examples/src/example_executor_convenience.c#L82

2020-04-28 08:12 UTC, ralph-lange commented on examples/uros_pingpong/uros_pingpong_main.c
> +  rcl_subscription_init(&ping_subscription, &node, ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Header), "/microROS/ping", &ping_subscription_ops);
Use rclc_subscription_init_default instead, to reduce the amount of boilerplate code, cf. https://github.com/micro-ROS/rclc/blob/master/rclc_examples/src/example_executor_convenience.c#L116

2020-04-28 08:12 UTC, ralph-lange commented on examples/uros_pingpong/uros_pingpong_main.c
> +  pthread_create(&guard_condition_thread, NULL, trigger_guard_condition, &guard_condition);
Is it possible to use a timer instead? Cf. https://github.com/micro-ROS/rclc/blob/master/rclc_examples/src/example_executor_convenience.c#L95

2020-04-28 08:12 UTC, ralph-lange commented on examples/uros_pingpong/uros_pingpong_main.c
> +    rcl_wait_set_clear(&wait_set);
This code can be simplified a lot by using the rclc Executor, cf. https://github.com/micro-ROS/rclc/blob/master/rclc_examples/src/example_executor_convenience.c#L134 to L172. Please feel free to ask @JanStaschulat for help in case of questions on the rclc Executor.

2020-06-11 09:56 UTC, julionce approved these changes

2020-07-21 10:27 UTC, merged